eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8282/eureka
    instance:
      hostname: ${vcap.application.uris[0]:localhost}
      instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

server:
  port: 9094

spring:
  cloud:
    gateway:
      routes:
        - id: employees-api
          uri: http://localhost:9092/
          predicates:
            - Path=/employees/**
        - id: workspace-api
            uri: http://localhost:9091/
            predicates:
              - Path=/workspaces/**

